### ISSUE TITLE
is Still active?

### ISSUE THREAD

**Issue by nixoncode** [FaaPz/PDO#105]
There haven't been many updates to this repo lately, issues are building up, even simple ones like #92.
## Is it still active?

**Comment by wowDaiver** [comment]
@nickhq Can I use your repo?

**Comment by nixoncode** [comment]
Not sure about this yet!

**Comment by mkraha** [comment]
I really like this, is this still active ? May i choose this for long time project?

**Comment by wowDaiver** [comment]
@krahamath I used it two years, everything is fine.
But there are some problems, for example, batch insert (multiinsert) and missing INSERT IGNORE

**Comment by mkraha** [comment]
Thank you @wowDaiver . I choosen to use illuminate/database

**Comment by mikegioia** [comment]
I'm maintaining an active fork of this repo here: https://github.com/ParticleBits/pdo

It has support for multiple inserts with on 'duplicate key update', and resolves all the open pull requests and issues. I'm using it and actively maintaining it, the namespace has changed though.

**Comment by kwhat** [comment]
Good Day,

I have been slowly working on the 2.x branch and I feel like it is getting very close to release-candidate status.  I would advise beginning the migration process to the 2.x branch sooner than later.  Version 2 is basically an entire rewrite of the 1.x branch that address some of the design shortfalls that were present in the original.  As far as the 1.x branch goes, that branch is/was maintained by Fabian but I am not sure where he has been as of late.  I would not count on the 1.x branch getting future updates.  I can merge code to this branch if we get community contributions, so @mikegioia if you want to maintain 1.x here, we can make that happen. 

P.S. @wowDaiver The insert ignore has been fixed in 2.x, the batch insert for multi records will probably come with 2.1.

**Comment by kwhat** [comment]
@nixoncode #92 has been resolved.
