### ISSUE TITLE
MS SQL (SQLSRV) INSERT null value

### ISSUE THREAD

**Issue by dotmra** [FaaPz/PDO#118]
Hi,

I am having a problem on 1.*
when I execute a query the NULL values becomes "" when binding values.

However MS SQL doesn't allow "" as an alias for NULL, it want NULL.

How can that be achieved?

**Comment by kwhat** [comment]
This should work as expected with escaped parameters.  With that said, I seem to remember a driver setting or PDO property that needed to be set for NULL on FreeTDS / PDO.  It has been a while since I have used MsSQL with PHP so I will have to look around for my notes to give you a definitive answer.
