### ISSUE TITLE
Should this composer package be named as "slim/pdo"?

### ISSUE THREAD

**Issue by jordikroon** [FaaPz/PDO#20]
To avoid confusion, I think it's best to rename this to a different name (faapz/slim-pdo?)
Devs may think that this is an official package maintained by Slim.

Any thoughts?

**Comment by FaaPz** [comment]
I do agree with you, @jordi12100. Back when I released Slim-PDO at Packagist, I wanted it to be recognised and used with the Slim Framework, so that's why I used their vendor name.

Now, Slim-PDO has "grown" and developers are using it in all kinds of projects, with all kinds of RDBMSes. Not only Slim Framework applications.

So yes, I'm going to re-release (the upcoming V2) under my own vendor name anytime soon. :wink:

**Comment by kwhat** [comment]
@FaaPz  I would be interested in contributing to 2.0.  Will you be creating a branch when you are ready to start development?

**Comment by FaaPz** [comment]
@kwhat Great! And yes, I will. :ok_hand:

**Comment by l0gicgate** [comment]
Hey @FaaPz, I'm a maintainer from the Slim Framework organization, I'm curious as to what this package has to do with Slim and why you hijacked our namespace. You should be using the `\FaaPz\PDO` namespace and not `\Slim\PDO`.

We would greatly appreciate if you could remove any mentions of the Slim Framework as this package has absolutely nothing to do with it. We're getting people asking for support via our communication channels as they think we're associated with this repository.

Thank you

**Comment by FaaPz** [comment]
@l0gicgate Sorry that I caused you any inconvenience! I've removed all mentions of the Slim Framework from this package and renamed both Composer & PHP vendor namespaces.

**Comment by l0gicgate** [comment]
Thank you @FaaPz, much appreciated!
